output_dir: ./experiment/

dataset:
  class: Drugbank
  path: ./data/
  split: random
  threshold: 30

task:
  class: classification
  model:
    class: CPINet
    param: 
      dim: 10
      layer_gnn: 3
      side: 5
      layer_cnn: 3
      layer_out: 3
      dropout: 0.1
  train: kfold

param_feature:
  radius: 2
  ngram: 3

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  device: [1]
  batch_size: 512

train:
  num_epoch: 1000

eval_metric: ['roc-auc', 'pr-auc', 'range_logAUC', 'accuracy', 'precision', 'recall', 'f1']
score_metric: f1