output_dir: ./experiment/

dataset:
  class: Drugbank
  path: ./data/
  split: random
  threshold: 30

task:
  class: classification
  model:
    class: GanDTI
    param: 
      features: 40
      GNN_depth: 3
      MLP_depth: 2 
      dropout: 0.1
  train: kfold

param_feature:
  radius: 2
  ngram: 3

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  device: [3]
  batch_size: 512

train:
  num_epoch: 1000

eval_metric: ['roc-auc', 'pr-auc', 'range_logAUC', 'accuracy', 'precision', 'recall', 'f1']
score_metric: f1