output_dir: ./experiment/

dataset:
  class: DAVIS
  path: ./data/
  split: random
  threshold: 30

task:
  class: classification
  model:
    class: AttentionDTI
  train: kfold

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  device: [2]
  batch_size: 64

train:
  num_epoch: 300

eval_metric: ['roc-auc', 'pr-auc', 'range_logAUC', 'accuracy', 'precision', 'recall', 'f1', 'rp@k', 'pr@k']
score_metric: f1