output_dir: ./experiment/

dataset:
  class: DAVIS
  path: ./data/
  split: random
  threshold: 30

task:
  class: classification
  model:
    class: IGTNet
    net:
      n_layers: 10
      n_heads: 8
      hidden_dim: 512
      out_dim: 512

      residual: True
      in_feat_dropout: 0.0
      dropout: 0.4
      layer_norm: False
      batch_norm: True

      pos_enc_dim: 8    # ignored by data; used in net
      in_dim_node: 88
      in_dim_edge: 24

      initial_mu: 4.0
      initial_dev: 1.0
      initial_alpha: 0.0
      initial_beta: 0.0
  train: kfold

optimizer:
  class: Adam
  lr: 5.0e-4
  init_lr: 0.0001
  lr_reduce_factor: 0.5
  lr_schedule_patience: 15
  min_lr: 1e-6
  weight_decay: 1e-5

engine:
  device: 0
  batch_size: 512

train:
  num_epoch: 300

eval_metric: [ 'roc-auc', 'pr-auc', 'range_logAUC', 'accuracy', 'precision', 'recall', 'f1', 'rp@k', 'pr@k' ]
score_metric: f1


