output_dir: ./experiment/

dataset:
  class: Drugbank
  path: ./data/
  split: random
  threshold: 30

task:
  class: classification
  model:
    class: IIFDTI
    param: 
      hid_dim: 64
      n_layers: 3
      kernel_size: 9
      n_heads: 8
      pf_dim: 256
      dropout: 0.1
  train: kfold

param_feature:
  ngram: 3

optimizer:
  class: Adam
  lr: 1.25e-4

engine:
  device: [3]
  batch_size: 32

train:
  num_epoch: 300

eval_metric: ['roc-auc', 'pr-auc', 'range_logAUC', 'accuracy', 'precision', 'recall', 'f1']
score_metric: f1