output_dir: ./experiment/

dataset:
  class: Human
  path: ./data/
  split: random
  threshold: 30

task:
  class: classification
  model:
    class: MATDTI7
    param:
      dropout: 0.1
      d_atom: 33
      d_model: 256
      # num_head: 16
  train: kfold
  
optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  device: [0]
  batch_size: 64

train:
  num_epoch: 1000

eval_metric: ['roc-auc', 'pr-auc', 'range_logAUC', 'accuracy', 'precision', 'recall', 'f1']
score_metric: f1