output_dir: ./experiment/

dataset:
  class: Drugbank
  path: ./data/
  split: random
  threshold: 30

task:
  class: classification
  model:
    class: TransCPI
    param: 
      protein_dim: 100
      atom_dim: 34
      hid_dim: 64
      n_layers: 3
      n_heads: 8
      pf_dim: 256
      dropout: 0.1
      kernel_size: 5

  train: kfold

param_feature:
  ngram: 3

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  device: [0]
  batch_size: 128

train:
  num_epoch: 300

eval_metric: ['roc-auc', 'pr-auc', 'range_logAUC', 'accuracy', 'precision', 'recall', 'f1']
score_metric: f1