name: bm
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - --find-links https://data.pyg.org/whl/torch-2.2.2+cu118.html
    - --find-links https://data.dgl.ai/wheels/torch-2.2/cu118/repo.html
    - deepchem==2.7.1
    - dgl==2.2.1+cu118
    - dgllife==0.3.2
    - easydict
    - gensim==4.3.3
    - networkx
    - numpy==1.24.4
    - pandas==2.1.3
    - pytdc==0.4.1
    - pyyaml
    - rdkit==2023.9.1
    - scikit-learn==1.3.2
    - scipy==1.8.1
    - selfies
    - subword-nmt
    - tensorflow==2.15.0.post1
    - torch==2.2.2+cu118
    - torch-cluster==1.6.3+pt22cu118
    - torch-geometric==2.4.0
    - torch-scatter==2.1.2+pt22cu118
    - torch-sparse==0.6.18+pt22cu118
    - torchdrug==0.2.1
    - tqdm
    - transformers==4.37.2
