output_dir: ./experiment/

dataset:
  class: DAVIS
  path: ./data/
  split: random
  threshold: 30

task:
  class: regression
  model:
    class: HGC
    param:
      dropout: 0.2
  train: kfold

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  device: [0]
  batch_size: 256

train:
  num_epoch: 400

eval_metric: ['mse', 'rmse', 'mae', 'r2', 'pcc', 'ci','spearman']
score_metric: mse