output_dir: ./experiment/

dataset:
  class: DAVIS
  path: ./data/
  split: random
  threshold: 30

task:
  class: regression
  model:
    class: MolTransformer
    param: 
      input_dim_drug: 23532
      input_dim_target: 16693
      max_drug_seq: 50
      max_protein_seq: 545
      emb_size: 384
      dropout_rate: 0.1
      scale_down_ratio: 0.25
      growth_rate: 20
      transition_rate: 0.5
      num_dense_blocks: 4
      kernal_dense_size: 3
      intermediate_size: 1536
      num_attention_heads: 12
      attention_probs_dropout_prob: 0.1
      hidden_dropout_prob: 0.1
      flat_dim: 78192
  train: kfold
  
optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  device: [1]
  batch_size: 32

train:
  num_epoch: 300

eval_metric: ['mse', 'rmse', 'mae', 'r2', 'pcc', 'spearman']
score_metric: mse